DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS friendship;

CREATE TABLE IF NOT EXISTS films (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name CHARACTER VARYING(50) NOT NULL,
	description CHARACTER VARYING(200) NOT NULL,
	release_date DATE NOT NULL,
	duration INTEGER NOT NULL,
	rate INTEGER NOT NULL,
	mpa_id INTEGER NOT NULL,
	CONSTRAINT films_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER NOT NULL AUTO_INCREMENT,
	email CHARACTER VARYING(50) NOT NULL,
	login CHARACTER VARYING(50) NOT NULL,
	name CHARACTER VARYING(50),
	birthday DATE NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS mpa (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT mpa_pk PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS genre (
	id INTEGER NOT NULL AUTO_INCREMENT,
	name CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT genre_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id INTEGER,
	genre_id INTEGER,
	PRIMARY KEY (film_id,genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
	film_id INTEGER,
	user_id INTEGER,
	PRIMARY KEY (film_id,user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
	user_one_id INTEGER,
	user_two_id INTEGER,
	PRIMARY KEY (user_one_id,user_two_id)
);